### ISSUE TITLE
CalendarView

### ISSUE THREAD

**Issue by emilylegg** [emilylegg/GluconfidenceApp#1]
As a user, I want to be able to see how many events I've had during the day including a summary of those events throughout the month. 

**Acceptance Criteria**

- The calendar view will show multiple events during the days of the month
- UI for a calendar
- Way to darken the circles around the calendar to show the increased number of events  
- Tapping will bring up the summary of the event (what fixed the event, what led up to the event)
- **BRIAN COMMENT:**  YES!  We want ability to see current month, but also if you swipe you can go back up to 6 months for past rolling history.  Make sense?

**Comment by LinBin01** [comment]
done
