### ISSUE TITLE
Last Three Lows Graph

### ISSUE THREAD

**Issue by emilylegg** [emilylegg/GluconfidenceApp#11]
As a user, I want to see my last three lows and show what was treated with Gluconfidence and what was not treated as Gluconfidence. 

**Acceptance Criteria**

- GraphUI
- Create three graphs to show the last three lows 
- Functionality showing Gluconfidence and Not Gluconfidence summaries
- Brian Comment:  We want to show a snapshot of the last 3 lows, and highlight below each graph a color coded comment that simply states the date/time of the low, and highlighted in ( BLUE) if GC was used to treat the low ( w GC logo timestamped on chart ) or RED if GC was not used. Please see the wire frame image. 
- 
![image](https://user-images.githubusercontent.com/77822266/109440151-3358a180-79ff-11eb-87c8-24d22ce718ef.png)

**Comment by LinBin01** [comment]
done
